id: I4258B87A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T10:25:14+00:00'
last_modified: '2022-06-08T06:10:45.100293+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20123
  title: ཐེག་པ་ཆེན་པོའི་མན་ངག་གི་བསྟན་བཅོས་ཡིད་བཞིན་རིན་པོ་ཆེའི་མཛོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BC33:
      image_group_id: I8LS20125
      title: ''
      total_pages: 626
      order: 1
      base_file: BC33.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
